### ISSUE TITLE
Feat Request : Color code only for dead and alive instead of actual words.

### ISSUE THREAD

**Issue by BaaridunNasr** [nikhil-RGB/Game-Of-Life-Basic#1]

**Comment by nikhil-RGB** [comment]
There is a colour coding for dead and alive cells, check the "additional
options" menu, and click on the "change colour scheme" Menu item.
Thank you for taking out the time to use my software!

**Comment by BaaridunNasr** [comment]
I meant that perhaps it would be better to remove the wording "Dead", "Alive" and provide a legend at the corner.

**Comment by nikhil-RGB** [comment]
> I meant that perhaps it would be better to remove the wording "Dead", "Alive" and provide a legend at the corner.

I thought it would be better with words, but this is a decent idea, will implement it later!
(It does look better without the words DEAD and ALIVE tbh)
